//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace compras.Datos1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invitado
    {
        public int Id_Invitado { get; set; }
        public int Numero_Empleado { get; set; }
        public int Id_Comedor { get; set; }
        public System.DateTime Fecha_Ingreso { get; set; }
        public int Folio { get; set; }
        public int Id_Usuario_Registo { get; set; }
        public System.DateTime Fecha_Registro { get; set; }
    }
}
