//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace compras.Datos1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kit
    {
        public int Id_Kit { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string Categoria { get; set; }
        public int Estatus { get; set; }
        public string Imagen { get; set; }
        public System.DateTime Fecha_Alta { get; set; }
        public int Usuario_Alta { get; set; }
        public Nullable<System.DateTime> Fecha_Actualizacion { get; set; }
        public Nullable<int> Usuario_Actualizacion { get; set; }
    }
}
