//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace compras.Datos1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reporte_Comedor
    {
        public int Id_Reporte_Comedor { get; set; }
        public System.DateTime Fecha_Entrada { get; set; }
        public int Numero_Empleado { get; set; }
        public string Compania { get; set; }
        public int Sede { get; set; }
        public int Id_Usuario_Acceso { get; set; }
    }
}
