//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace compras.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kit_Producto
    {
        public int Id_Kit_Producto { get; set; }
        public int Id_kit { get; set; }
        public int Id_Producto { get; set; }
    }
}
