//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace compras.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orden_Compra
    {
        public int Id_Compra { get; set; }
        public int Folio { get; set; }
        public int Usuario { get; set; }
        public int Estatus { get; set; }
        public decimal Costo { get; set; }
        public System.DateTime Fecha_Alta { get; set; }
    }
}
